### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by iliastsangaris** [cmswalker/Project_One#11]
Is the app deployed somewhere?

**Comment by cmswalker** [comment]
thanks for this, totally forgot.  Been so busy (got a job this week!)

On Wed, Aug 19, 2015 at 5:18 PM, Ilias Tsangaris <notifications@github.com>
wrote:

> Is the app deployed somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmswalker/Project_One/issues/11>.
>



-- 
Michael Walker
cmswalker.github.io
